server:
  port: 4001

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #利用服务名进行路由
    routes:
      - id: payment_routh  #路由id，建议服务名
        url: lb://cloud-payment-service #路由url
        predicates:
          - Path=/payment/get/**


eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

